version: '3.2'                                                                                                                                                                                                                                
services:
  ex_merchant:
    image: "golang:1.18.2"
    hostname: "ex_merchant"
    restart: "on-failure:3"
    working_dir: "/go"
    volumes:
      - "/data/code/7ex.art/merchant:/go"
    command: "./ex_merchant"
    extra_hosts:
      - "secret-pay.7ex.art:172.88.88.11"
      - "secret-passport.7ex.art:172.88.88.12"
      - "secret-mall.7ex.art:172.88.88.13"
      - "secret-copyright.7ex.art:172.88.88.14"
      - "secret-pay.cex.art:172.88.88.11"
      - "secret-passport.cex.art:172.88.88.12"
      - "secret-mall.cex.art:172.88.88.13"
      - "secret-copyright.cex.art:172.88.88.14"
    networks:
      7ex-network:
        ipv4_address: "172.88.88.15"
    container_name: "ex_merchant"

networks:
  7ex-network:
    external:
      name: "7ex_network" 
