version: '3.2'                                                                                                                                                                                                                                
services:
  ex_open:
    image: "golang:1.18.2"
    hostname: "ex_open"
    restart: "on-failure:3"
    working_dir: "/go"
    volumes:
      - "/data/code/7ex.art/open:/go"
    command: "./7ex_open"
    extra_hosts:
      - "secret-pay.7ex.art:172.88.88.11"
      - "secret-passport.7ex.art:172.88.88.12"
      - "secret-mall.7ex.art:172.88.88.13"
      - "dev-secret-mall.360ex.art:172.88.88.13"
    networks:
      7ex-network:
        ipv4_address: "172.88.88.111"
    container_name: "ex_open"

networks:
  7ex-network:
    external:
      name: "7ex_network" 
