version: '3'
services:
  elasticsearch:
    image: elasticsearch:7.5.1
    container_name: elasticsearch
    volumes:
      - ./elasticsearch/data:/usr/share/elasticsearch/data　　#这里将elasticsearch的数据文件映射本地，以保证下次如果删除了容器还有数据
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
    networks:
      - es-jaeger
  kibana:
    image: docker.elastic.co/kibana/kibana:7.5.1
    environment:
      SERVER_NAME: kibana
      ELASTICSEARCH_HOSTS: http://192.168.71.26:9200
    #volumes:
      #- ./kibana/config:/usr/share/kibana/config
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - es-jaeger
networks:
  es-jaeger:
    driver: bridge