version: '3'
services:
  elasticsearch:
    image: elasticsearch:7.5.1
    container_name: elasticsearch
    volumes:
      - ./elasticsearch/data:/usr/share/elasticsearch/data　　#这里将elasticsearch的数据文件映射本地，以保证下次如果删除了容器还有数据
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
    networks:
      - es-jaeger
  kibana:
    image: docker.elastic.co/kibana/kibana:7.5.1
    environment:
      SERVER_NAME: kibana
      ELASTICSEARCH_HOSTS: http://192.168.71.26:9200
    #volumes:
      #- ./kibana/config:/usr/share/kibana/config
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - es-jaeger
  jaeger-collector:
    image: jaegertracing/jaeger-collector:1.28
    container_name: jaeger-collector
    environment:
      - SPAN_STORAGE_TYPE=elasticsearch
      - ES_SERVER_URLS=http://192.168.71.26:9200
      - LOG_LEVEL=debug
    networks:
      - es-jaeger
    ports:
      - "14369:14269"
      - "14250:14250"
      - "14268:14268"
      - "9411:9411"

  jaeger-agent:
    image: jaegertracing/jaeger-agent:1.28
    container_name: jaeger-agent
    environment:
      - REPORTER_GRPC_HOST_PORT=192.168.71.26:14250
      - LOG_LEVEL=debug
    ports:
      - "5775:5775/udp"
      - "5778:5778/tcp"
      - "6831:6831/udp"
      - "6832:6832/udp"
    networks:
      - es-jaeger
    depends_on:
      - jaeger-collector
  jaeger-query:
    image: jaegertracing/jaeger-query:1.28
    container_name: jaeger-query
    environment:
      - SPAN_STORAGE_TYPE=elasticsearch
      - ES_SERVER_URLS=http://192.168.71.26:9200
      - LOG_LEVEL=debug
    ports:
      - "16686:16686"
      - "16687:16687"
    networks:
      - es-jaeger
networks:
  es-jaeger:
    driver: bridge