version: '3'

services:
  nacos:
    image: nacos/nacos-server
    # 容器名称
    container_name: nacos
    # 端口映射
    ports:
      - 8848:8848
      - 9848:9848
      - 9849:9849
    # 容器权限
    privileged: true
    # 参数设置
    environment:
      JVM_XMS: 256m
      JVM_XMX: 256m
      MODE: standalone
      PREFER_HOST_MODE: hostname
    volumes:
      - ./logs:/home/nacos/logs
      - ./init.d/custom.properties:/home/nacos/init.d/custom.properties
      - ./nacos_data:/home/nacos/data
